import { app, BrowserWindow, globalShortcut, Tray, Menu } from 'electron';
import { exec } from 'child_process';
// import { homedir } from 'os';
// import { join } from 'path';
import { readFileSync } from 'fs';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
// declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let tray: Tray | null = null
let window: BrowserWindow | null = null;
let commands: any = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): Promise<void> => {
  window = new BrowserWindow({
    height: 500,
    width: 700,
    frame: false,
    fullscreenable: false,
    resizable: false,
    movable: false,
    transparent: true,
    show: true,
  });
  window.setVisibleOnAllWorkspaces(true);

  const url = `${ MAIN_WINDOW_WEBPACK_ENTRY }`;

  return window.loadURL(url);
};

app.on('ready', async () => {
  app.dock.hide();

  // const home = homedir();
  // const filePath = join(home, 'projects/commands/src', 'commands.json');
  const fileContent = readFileSync('src/commands.json', 'utf-8');
  commands = JSON.parse(fileContent);
  console.log(commands);

  Object.keys(commands).forEach((key) => {
    globalShortcut.register(key, () => {
      console.log(`running ${ commands[key] } from input ${ key }`);
      exec(commands[key]);
    });
  });

  await createWindow();

  globalShortcut.register('Command+Shift+Space', () => {
    toggle();
  });

  const menu = Menu.buildFromTemplate([
    { role: 'quit', label: 'Quit Commands', accelerator: 'Command+Q' },
  ]);

  if (!tray) {
    tray = new Tray('src/icon.png');
  }

  tray.setContextMenu(menu);
});


const toggle = () => {
  console.log(`open input event`);

  if (window.isFocused()) {
    window.hide();
  } else {
    window.show();
  }
}


app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
